springdoc:
  packagesToScan: com.example.a
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: false
    path: /swagger-ui # 접속 path 설정
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
  use-fqn: true